# Generated by Django 4.2.8 on 2023-12-19 11:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='publication_date',
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='deskripts',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='quentiny',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
